# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/dh-illnesses',
                'doc_host': 'https://matt.github.io',
                'git_url': 'https://github.com/matt/dh-illnesses',
                'lib_path': 'dh_illnesses'},
  'syms': {'dh_illnesses.core': {'dh_illnesses.core.foo': ('core.html#foo', 'dh_illnesses/core.py')}}}
