# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/00_core.ipynb 3
import pandas as pd
from fastcore.test import *
from fastcore.utils import *
import pyspssio

# import raine_tools as rn
from data_harmonising.data import *

from src.config import WORKBOOK, SHEETNAME

# %% ../nbs/00_core.ipynb 6
assert 1 == 1
